### ISSUE TITLE
Stupid copy related question: $(RuntimeID) doesn't seem to be defined

### ISSUE THREAD

**Issue by philstopford** [picoe/Eto.Veldrid#12]
Trying to use this inside my previously-OpenTK.Eto project : 

"C:\Users\phil\.nuget\packages\veldrid.spirv\1.0.9\runtimes\\native\" to the destination file "bin\Debug\netstandard2.0\", because the destination is a folder instead of a file. To copy the source file into a folder, consider using the DestinationFolder parameter instead of DestinationFiles.

I can't see why $(RuntimeID) isn't defined (which seems to be the issue above):

  <Target Name="CopyVeldridSpirvNative" AfterTargets="SetPaths" BeforeTargets="NeatenizeLibraries" Condition="!$(NoCopyVeldridSpirvNative.Contains($(MSBuildProjectName)))">
    <Copy
      SourceFiles="$([MSBuild]::EnsureTrailingSlash('$(NuGetPackageRoot)'))veldrid.spirv\$(VeldridSpirvVersion)\runtimes\$(RuntimeID)\native\$(VeldridSpirvNativeName)"
      DestinationFolder="$(VeldridSpirvNativePath)" />
  </Target>

**Comment by ItEndsWithTens** [comment]
Did you update the IsWindowsProject/IsLinuxProject/IsMacProject logic in Directory.Build.targets to look for the name of your project instead of 'Eto.Veldrid.WinForms' and so on? Hardcoding the project names associated with various platforms was the best way I could come up with to do that (retrieving the current build platform wouldn't be ideal, since Eto projects can be built on a different OS than they'll eventually run), but it does create the burden of updating them for every project where one might want to use them.

**Comment by philstopford** [comment]
Yes, I think so. One of my complexities is that I'm sharing a common 'DesignLibs' location across multiple derived tools, so the common infrastructure is located under ../../DesignLibs 

I'm noticing that the DLLs from this location are not being copied over in this new structure, even if I delete the contents of the target bin/Debug folder.

**Comment by ItEndsWithTens** [comment]
Another possibility I hadn't considered earlier is that you'll need to add the names of any projects that aren't the final GUI applications to the NoCopyVeldridSpirvNative property, for example:
```xml
<PropertyGroup>
  <NoCopyVeldridSpirvNative>MyCoolLibrary;Etcetera</NoCopyVeldridSpirvNative>
</PropertyGroup>
```
It's clunky, and in the long term I want to find a better solution, but I did that for this exact reason; library projects aren't necessarily platform-specific, and won't set any of the IsXProject booleans, leading to no native library being copied.

If you've already tried that, I'm not sure what's happening. I also can't say why your DesignLibs wouldn't be copied, either. If you're willing and able to share the project (privately through email, if necessary) I could take a look at it.
