### ISSUE TITLE
Veldred worth-it to go for?

### ISSUE THREAD

**Issue by TomQv** [picoe/Eto.Veldrid#20]
Hi Curtis,
with Big Sur the point of serious consideration has come. Our apps build with Eto are using OpenGL for the graphics and now its starting to become funny and strange with new macOS.
Just from first impression Veldred seems to be a good way to go for portable graphics on .Net for Windows, Mac, iOS and Droid.
But three years ago I thought the same with OpenGL.
You are supporting Veldred with a Eto-lib. How serious is this? What is your impression about Veldred?

Tom

**Comment by cwensley** [comment]
@TomQv I am supporting it, yes.  Initial impressions is that it is a good alternative instead of creating your own wrappers around the various 3D toolkits for .NET, and is being updated somewhat regularly.

 I'm not sure how to explain how "serious" this is though. 🤷🏻‍♂️
