### ISSUE TITLE
Vulkan on Linux shows a black viewport and has DPI issues

### ISSUE THREAD

**Issue by philstopford** [picoe/Eto.Veldrid#22]
Ubuntu 20.10, high DPI, forcing vulkan gives me several different results depending on situation : 

- If I use the Eto.Veldrid test, I get a black panel.
- If I use my plot test (DesignLibs_GPL), the high DPI results in the content being confined to the top right of the panel. This is only visible whilst dragging. After painting is done, the panel contents go black. During dragging, a flicking between this black panel and the plot is seen.

Curiously, I don't see this problem with the intel drivers for the intel 620 GPU in my 7600U based laptop. The above is for my nVidia 1080 with 460 and earlier series drivers.

**Comment by cwensley** [comment]
Thanks for reporting these issue(s).  As for it showing only in the top right, it appears Eto.Forms.Window.LogicalPixelSize is not returning the right thing (Screen.LogicalPixelSize does though).  I'll get that fixed up in Eto.  

As for the black panel issue, I am not sure what is going on there.  I could poke around, but without being able to reproduce it I'd just be guessing.

**Comment by philstopford** [comment]
This looks to be OK.
