### ISSUE TITLE
Vulkan (Linux) testing.

### ISSUE THREAD

**Issue by philstopford** [picoe/Eto.Veldrid#4]
Vulkan seems to be supported on my host system.

[vulkaninfo.txt](https://github.com/ItEndsWithTens/Eto.Veldrid/files/3631406/vulkaninfo.txt)

The Vulkan smoketest also runs happily.

Post-build, the library look-up fails because it's seeking 'libvulkan.so' where 'libvulkan.so.1' is available. I made a symlink to sort this out. Now forcing the backend to Vulkan (because it seems to fall to OpenGL otherwise), and trying to run with Vulkan under Linux Mint : 

{System.NullReferenceException: Object reference not set to an instance of an object

"  at PlaceholderName.GtkVeldridSurfaceHandler.InitializeOtherApi () [0x00001] in /home/phil/Desktop/Eto.Veldrid-master/src/gui/Eto.Veldrid.Gtk/Program.cs:256 \n  at PlaceholderName.VeldridSurface.InitializeOtherApi () [0x000aa] in /home/phil/Desktop/Eto.Veldrid-master/src/Eto.VeldridSurface/VeldridSurface.cs:341 \n  at PlaceholderName.VeldridSurface.InitializeGraphicsApi () [0x00040] in /home/phil/Desktop/Eto.Veldrid-master/src/Eto.VeldridSurface/VeldridSurface.cs:302 \n  at PlaceholderName.VeldridSurface.set_ControlReady (System.Boolean value) [0x00008] in /home/phil/Desktop/Eto.Veldrid-master/src/Eto.VeldridSurface/VeldridSurface.cs:248 \n  at PlaceholderName.VeldridSurface.<.ctor>b__44_0 (System.Object sender, System.EventArgs e) [0x00000] in /home/phil/Desktop/Eto.Veldrid-master/src/Eto.VeldridSurface/VeldridSurface.cs:284 \n  at Eto.PropertyStore.TriggerEvent[T] (System.Object key, System.Object sender, T args) [0x0000e] in <6db481985cca4510b36c8dbd12852b82>:0 \n  at Eto.Forms.Control.OnLoadComplete (System.EventArgs e) [0x00006] in <6db481985cca4510b36c8dbd12852b82>:0 \n  at Eto.Forms.Control.TriggerLoadComplete (System.EventArgs e) [0x0000c] in <6db481985cca4510b36c8dbd12852b82>:0 \n  at Eto.Forms.Container.OnLoadComplete (System.EventArgs e) [0x00028] in <6db481985cca4510b36c8dbd12852b82>:0 \n  at Eto.Forms.Form.Show () [0x0001e] in <6db481985cca4510b36c8dbd12852b82>:0 \n  at Eto.Forms.Application+<>c__DisplayClass47_0.<Run>b__0 (System.Object sender, System.EventArgs e) [0x0001c] in <6db481985cca4510b36c8dbd12852b82>:0 \n  at Eto.PropertyStore.TriggerEvent[T] (System.Object key, System.Object sender, T args) [0x0000e] in <6db481985cca4510b36c8dbd12852b82>:0 \n  at Eto.Forms.Application.OnInitialized (System.EventArgs e) [0x00006] in <6db481985cca4510b36c8dbd12852b82>:0 \n  at Eto.Forms.Application+Callback.OnInitialized (Eto.Forms.Application widget, System.EventArgs e) [0x0000c] in <6db481985cca4510b36c8dbd12852b82>:0 \n  at Eto.GtkSharp.Forms.ApplicationHandler.Run () [0x0002c] in <5067fd7d51d748d8bac94326932fe67c>:0 \n  at Eto.Forms.Application.Run (Eto.Forms.Form mainForm) [0x0002c] in <6db481985cca4510b36c8dbd12852b82>:0 \n  at PlaceholderName.MainClass.Main (System.String[] args) [0x0004c] in /home/phil/Desktop/Eto.Veldrid-master/src/gui/Eto.Veldrid.Gtk/Program.cs:287 "

**Comment by ItEndsWithTens** [comment]
Ugh, yikes, Github doesn't play nice with issue/PR numbers across repos. Just a note to clarify that "pushed a commit that referenced this issue", I was just synchronizing my 'philstopford' branch with your fork, so as to be on the same page, and because the merge commits reference PR #4 from your repo, they connect to issue #4 on this repo, since Github doesn't sync issues across forks. Harmless, but strange, and something to keep in mind to avoid confusion. Trips me up every time.

In any event, my system doesn't support VT-x so I can't use Vulkan in a VM, but I'm working on a Linux dual boot that should do the trick. It's something I've wanted to do anyway, so now's as good a time as any.

**Comment by philstopford** [comment]
Closing this, all seems to be good.
